services:
  web:
    build: .
    ports:
      - "${PORT:-8080}:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mariadb:10.4
    environment:
      - DB_HOST=db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: packmates
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  db_data:
